### ISSUE TITLE
Manchester Code

### ISSUE THREAD

**Issue by klarlichter** [rfkd/aircontrol#1]
Hello,
we are using your great aircontrol. 
But how we can get the right Manchester code? We create a scn file. But we are not able to get the right code. Could you help please?:(

**Comment by rfkd** [comment]
Hello,

could you upload your scan somewhere or show me some details? Which remote control type are you trying to scan? Otherwise I'm not really sure how to help you.

Here's how to use the scan mode generally:
* Prepare the command (in combination with tee to log into a file) on the command line but do not execute it yet.
* Take the remote control in your hands.
* Execute the prepared command line and press and hold the button you want to scan shortly after (<1s).
* Release the button once the aircontrol scan has completed.
* Open the file. At the beginning you will only see "random noise" but if you scroll down you should see a somehow repeating pattern - this is where the actual radio command starts.

When analyzing Manchester encoding you have to look at level changes, see the last example in the 'target' section of the README file. Typically there is a "longer" period with a constantly low or high level when a command starts or ends.

**Comment by Seppelchen** [comment]
Hello,
Could Insignia Details via Email? If yes where i Could submit our Mail ? I will submit scn file in Email.

**Comment by rfkd** [comment]
Please post an example to a site like www.pastebin.com - this might help others as well.

**Comment by Seppelchen** [comment]
Hello, 
we had create a new paste. :)
Please take a look into: http://pastebin.com/nUnsjRNi
There you can see a manchester - code. 
We had create a scn file with value of 1000.

But we dont know how we get the correct code now..:(

**Comment by rfkd** [comment]
Please also answer the following questions:
* What is your scan duration (-s parameter value)? 1000ms, i.e. 1s?
* What is your configured sampling rate (samplingRate parameter in the 'scan' section of your configuration)? 100us?
* Which device are you scanning? A Warema EWFS shutter remote?

Given the above assumptions I would assume that the signal starts at line 400 and ends at line 905:
* The high period between lines 400 and ~430 is a '**S**'.
* The high to low transition at line 436 is a '**0**' (going from ~431 to ~442).
* The low to high transition at line 448 is a '**1**' (going from ~443 to 454)
* The next low to high transition at line 460 is another '**1**' (going from 455 to 467).
* The low to high transition at line 473 again adds a '**1**' (going from 468 to 478).
* The high to low transition at line 484 adds a '**0**' (going from 479 to 489).

And so on, the rest is just a diligent but routine piece of work. If this is really a Warema EWFS (as it seems to be) your airCommand will look like the following in the end (remaining dots replaced by zeros and ones of course).

```
airCommand =
		"S01110........."
		"S........."
		"S........."
		"S";
```

**Comment by Seppelchen** [comment]
Hello,
now the answer regarding your questions:
1. aircontrol - s 1000 > warema.scn
2. samplingRate -> 100
3. Warema EWFS right

But could you re post the airCommand please. Best, if you can edit our pastebin Code and write behind the values, that I can see and learn. Because we had try and it wont work :'(

**Comment by rfkd** [comment]
Show me how far you came and tell me about your problems or what you didn't understand in my answer above. Have a look at the pastebin site and my analysis at the same time (next to each other or even printed) to get the logic behind it. It is important that you know how things work as you have probably more than one command to analyze.

**Comment by Seppelchen** [comment]
Hello,
I had try and get this result:

scan:
{
        /* GPIO pin to use for scanning (Broadcom GPIO numbers, not re-mapped) */
        gpioPin = 18;

        /* Delay between two samples, unit: us */
        samplingRate = 100;
};

/** This section defines target defaults which can be overridden in the target
 * sections.
 */
target:
{
        /* GPIO pin to use for target control (Broadcom GPIO numbers, not
         * re-mapped) */
        gpioPin = 17;

        /* Data pulse length (total length of a single 0/1 element), unit: us */
        dataLength = 1780;

        /* Sync time length (total length of a single s/S element), unit: us */
        syncLength = 5000;

        /* Number of command transmissions */
        sendCommand = 20;

        /* Delay between command transmissions, unit: us */
        sendDelay = 25000;

        /** Radio frame encoding (0: Manchester, 1: Remote Controlled Outlet)
         *                   _           _               _
         * Manchester:    0)  |_    1) _|     s) _    S)
         *                                  _            ___
         * Remote Controlled Outlet:    0) | |___    1) |   |_
         *  (for reference: 00 -> 0, 11 -> 1, 01 -> F)
         *
         * This setting defines valid airCommand values.
         */
        airCode = 0/*Manchester*/;
};

/** Target sections.
 */

warema_sample:
{
        /* Air command to be transmitted (values defined by airCode) */
        airCommand =
                "S01110100001"  // Command
                "S010010111"            // Device
                "S00110011"             // Device
                "S";
};

But it seems not working...:(

**Comment by rfkd** [comment]
Have a look at this corrected pastebin (I cannot edit yours): http://pastebin.com/rP01rdDY

According to it the airCommand should be as follows:
```
airCommand =
        "S01110100111111"
        "S010110100"
        "S000110110"
        "S";
```

The problem with yours was that you ignore the Manchester structure. Each level change has a plateau before **and** after the level change so you must take this into account. In some cases you were ignoring this and just counting edges.

**Comment by Seppelchen** [comment]
Hello,
i had paste this but nothing happen...:'(
Rest of code:

#/* aircontrol configuration file */

/** This section defines the air scan parameters.
 */
scan:
{
        /* GPIO pin to use for scanning (Broadcom GPIO numbers, not re-mapped) */
        gpioPin = 18;

        /* Delay between two samples, unit: us */
        samplingRate = 100;
};

/** This section defines target defaults which can be overridden in the target
 * sections.
 */
target:
{
        /* GPIO pin to use for target control (Broadcom GPIO numbers, not
         * re-mapped) */
        gpioPin = 17;

        /* Data pulse length (total length of a single 0/1 element), unit: us */
        dataLength = 1780;

        /* Sync time length (total length of a single s/S element), unit: us */
        syncLength = 5000;

        /* Number of command transmissions */
        sendCommand = 20;

        /* Delay between command transmissions, unit: us */
        sendDelay = 25000;

Where we can figure out whats going wrong?

**Comment by rfkd** [comment]
In the future please use the github code markup when pasting something as the stuff you pasted is not really readable (put 3x ` before and after the paste, see "Styling with Markdown" above the answer edit field).

My Warema pulse configuration is the same as yours, so that should not be the problem. You can try playing around with the `sendCommand` and `sendDelay` parameters.

Are you sure the hardware is wired/working correctly and the configured target pin is connected to the data line of the transmitter? This might also be a problem with the distance between sender and shutters and/or the antenna setup. You soldered an antenna to the transmitter with a length of 17cm (lambda/4), right? If so, also try moving the sender around (also with different antenna angles). At some point the shutters should show some reaction.

Try to open 2 command line sessions, 1 transmitting and 1 scanning, and verify the output. That way you can ensure that the right thing is being sent. If this is correct this is definitely a hardware issue.

**Comment by Seppelchen** [comment]
Hello,
ok i had try the following:
aircontrol.conf is located under /etc/aircontrol.conf
if I run 
```sudo aircontrol -t warema_sample```
it will use etc/aircontrol.conf .

The Code from your prev. post i had used.

```
/* aircontrol configuration file */

/** This section defines the air scan parameters. 
 */
scan:
{
	/* GPIO pin to use for scanning (Broadcom GPIO numbers, not re-mapped) */
	gpioPin = 18;

	/* Delay between two samples, unit: us */
	samplingRate = 100;
};

/** This section defines target defaults which can be overridden in the target
 * sections.
 */
target:
{
	/* GPIO pin to use for target control (Broadcom GPIO numbers, not
	 * re-mapped) */
	gpioPin = 17;

	/* Data pulse length (total length of a single 0/1 element), unit: us */
	dataLength = 1780;	

	/* Sync time length (total length of a single s/S element), unit: us */
	syncLength = 5000;	

	/* Number of command transmissions */
	sendCommand = 10;
	
	/* Delay between command transmissions, unit: us */
	sendDelay = 10000;
	
	/** Radio frame encoding (0: Manchester, 1: Remote Controlled Outlet)
	 *                   _           _               _
	 * Manchester:    0)  |_    1) _|     s) _    S)
	 *                                  _            ___
	 * Remote Controlled Outlet:    0) | |___    1) |   |_
	 *  (for reference: 00 -> 0, 11 -> 1, 01 -> F)
	 *
	 * This setting defines valid airCommand values.
	 */ 
	airCode = 0/*Manchester*/;
};

/** Target sections.
 */

warema_sample:
{
	/* Air command to be transmitted (values defined by airCode) */
	airCommand =
	"S01110100111111"
        "S010110100"
        "S000110110"
        "S";
};
```

If I using playing around sendCommand and sendDelay it wont working too.
I also had try use 433MHZ sender 10 cm from our WAREMA Window nothing happen....

I open 2 command lines and try your idea i can see that our code are in that scan.
But sometihing i think maybe it wont know should it be up or down?

I also I think I connect pin correct. Data Line will go into (please look at this http://www.mikrocontroller.net/attachment/267571/GPIO_Raspberry_2.jpg ) GPIO 17 (number 11, 6th from top on left side)

How we can debug or find a solution? :(

**Comment by rfkd** [comment]
For full shutter movements (like going completely up/down or stopping - opposed to just stepping for shading reasons) I use the following parameters:
```
dataLength = 1780;
syncLength = 5000;
sendCommand = 20;
sendDelay = 25000;
```
To move the shutters in steps I decreased the `sendCommand` value to `5` (this is a separate target in my configuration).

> I open 2 command lines and try your idea i can see that our code are in that scan.
> But sometihing i think maybe it wont know should it be up or down?

What do you mean by that? A transmitted signal sent by aircontrol should not differ to the one sent by the remote control unit. Does it differ? If so, what is the difference (maybe upload to pastebin)?

Did you solder a 17cm antenna to the transmitter PCB?

Do you have another transmitter you could test? Maybe your unit is broken.

**Comment by Seppelchen** [comment]
Hello,

it is the same code sir. I and and get the same code. So it seems ok with send.
And we also test before plight to send code to intertechno and it is also working. So I think unit should be ok. Is that true?
And we are using no antenna. Did we need some antenna ? Because if we try to use raspberry 10 cm from device we would control it will also not working. :(

Am 05.01.2016 um 00:27 schrieb rfkd <notifications@github.com<mailto:notifications@github.com>>:


For full shutter movements (like going completely up/down or stopping - opposed to just stepping for shading reasons) I use the following parameters:

dataLength = 1780;
syncLength = 5000;
sendCommand = 20;
sendDelay = 25000;


To move the shutters in steps I decreased the sendCommand value to 5 (this is a separate target in my configuration).

I open 2 command lines and try your idea i can see that our code are in that scan.
But sometihing i think maybe it wont know should it be up or down?

What do you mean by that? A transmitted signal sent by aircontrol should not differ to the one sent by the remote control unit. Does it differ? If so, what is the difference (maybe upload to pastebin)?

Did you solder a 17cm antenna to the transmitter PCB?

Do you have another transmitter you could test? Maybe your unit is broken.

**Comment by rfkd** [comment]
Actually I've ordered two pairs of 433 MHz transmitter and receiver PCBs on eBay for ~2€ each from China about 2 years ago. I don't have a link any more but if you can control your power outlets your transmitter should be working. 

My antenna is home-made. At the beginning I was simply using a solid copper wire (not a stranded wire) from my houses electric installation. Isolation doesn't matter, just the length of 17cm is important.

In my opinion it's definitely worth trying to solder such an antenna to the transmitter as you would need it anyways as soon as you want to control all shutters in your home. In my setup I am even using 2 transmitters with grounded antennas in different angles to improve the radio stability.

**Comment by Seppelchen** [comment]
Hello, 

what should we do / can we do that your tool will submit code to receiver ? Did we need antenna? Or will it also working without this antenna ? Because we had place raspberry in near of our shutter. (10cm from this) but no reaction. :( Or will it only work with antenna?

**Comment by rfkd** [comment]
I'm not sure but if you scan the same code as when using the remote control the program and the transmitter seem to work fine. As I said I would solder an antenna to the transmitter and try sending the command from different antenna locations and angles.

**Comment by Seppelchen** [comment]
Hello,
i will prepare 433 MHZ sender within 3 hours from now with an antenna.
Could you also repost a aircontrol.conf example what you are using that shutter can go up or shutter can go down?

**Comment by Seppelchen** [comment]
Hello,
now I had try another solution with antenna and it will also not working.

I also had try another device no reaction from another window.
 My Manchester-Code:
``` 
       airCommand =
        "S01110100111111"
        "S001100100"
        "S01001010"
        "S";
```

Pastebin file: http://pastebin.com/uNp7xm8d

Is this true Code? Or something wrong?

**Comment by rfkd** [comment]
You made two little mistakes before the S-plateaus, fixed version is here: http://pastebin.com/hmuNZKgG
```
airCommand =
        "S01110100111111"
        "S001100100"
        "S010010101"
        "S";
```
It's easy to find such errors by checking the number of code characters - they only differ in value between targers of the same hardware type but not in their total count.

Unfortunately I'm not really sure what you could do now. I think I'd grab an oscilloscope and really compare the signals sent by the remote control unit to the ones sent by aircontrol. Maybe some timing tweaks are needed.

**Comment by Seppelchen** [comment]
What does it mean? :? 
Could you develop some work around to figure out.

**Comment by rfkd** [comment]
Get an oscilloscope and analyze both signals at the receiver side. I don't have any more ideas, sorry.

**Comment by Seppelchen** [comment]
Hello thank you for help. I think I will stop working on this.
