### ISSUE TITLE
can't get a proper plot

### ISSUE THREAD

**Issue by Blackspell01** [rfkd/aircontrol#24]
Im trying my best to work with the readme file but I think im missing out something important...
It says I should use the tee command to get a plot. Please tell me how to perform this step.
Currently im using ./aircotrol -d scan -s 1000.
My output is https://pastebin.com/06X7E1ZW

When reading through other topics, im expecting something like this: http://pastebin.com/hmuNZKgG

What am I doing wrong or is my Pi or the receiver broken?

Thanks for your help!

**Comment by rfkd** [comment]
Unfortunately I cannot access the output on the first pastebin link, it says `Error, this is a private paste or is pending moderation.`. But what exactly are you trying to achieve and which hardware are you trying to control? Do you want to use the replay feature or analyze a signal to define a target section in the configuration? I'm asking since you're specifying the `-d` argument for creating a replay-comptible air scan dump but expecting an ASCII graph.

To check whether your receiver is working (and configured) correctly just run `aircontrol -s 1000`. Don't send anything e.g. with a wireless remote during that time. After one second you should see the expected ASCII graph and it should show environmental noise - a flat line, may it be high or low, indicates a problem. Checking the sender is not so straightforward, you could generate an interfering signal by configuring and executing a longer target and see whether the remote control is still working fine during execution (this is usually not the case if the sender is disturbing the remote control signal).

Once you're sure the hardware is working as expected you can try out the air replay feature. Prepare the command line `aircontrol -d scan.asd -s 1000` but don't execute it yet. Take the remote control to be scanned in your hands, hit the return key in the terminal and press the desired remote control key at the same time. Once the air scan dump has been created you can try to replay it with `aircontrol -r scan.asd`.

If you instead want to analyze the signal by yourself and configure it properly (the better way), you have to capture the output of the scan **without** `-d` argument: `aircontrol -s 1000 | tee scan.log`. It requires knowledge about the used signal encoding type and timing though - it is much easier to do this with a signal analyzer or an oscilloscope.

**Comment by Blackspell01** [comment]
Thank you so much for your detailed answer! For some reason I thought I'd have to use -d to get the plot output. Now it works as expected. Thanks again! I'm trying to decode warema codes btw.
